version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    groups:
      vitest:
        patterns:
          - vitest
          - '@vitest/*'
    allow:
      - update-types:
          - version-update:semver-major
    allow:
      - dependency-name: tree-sitter-java-orchard
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
